### ISSUE TITLE
Fatal error: Interface 'RenderableAsPortlet' not found 

### ISSUE THREAD

**Issue by Legin76** [gordonbanderson/ss3gallery#1]
Hi

Using silverstripe 3.1.16, after uploading the files, when I run /dev/build?flush=ALL I get the error below.

Fatal error: Interface 'RenderableAsPortlet' not found in /home/swimming/public_html/ss3gallery/code/GalleryImage.php on line 4

**Comment by gordonbanderson** [comment]
OK, that's a missing module dependency.  I've uploaded a heap of modules recently and haven't had time to test them all.  This one is marked as build failing I notice.  Fixing...

**Comment by Legin76** [comment]
Fab thanks...

**Comment by gordonbanderson** [comment]
Looks like I need to fix sub module dependencies and the SEO extension is also tripping up on tests, though that one is not my fault :)

To get going for now, and I will fix from composr ASAP clone the following:

```
 git clone git@github.com:gordonbanderson/weboftalent-portlets.git portlets
 git clone git@github.com:gordonbanderson/Mappable.git mappable
 git clone git@github.com:gordonbanderson/page-with-image.git pagewithimage
 git clone git@github.com:gordonbanderson/weboftalent-twitter-tools.git twitter-tools
 git clone git@github.com:gordonbanderson/silverstripe-liveseo.git seo
```

SEOSiteTreeExtension.php is breaking for me during the build, temporarily comment out lines that break.  I have to go out now, will endeavour to fix in next 24 hrs or so for a clean composer install

**Comment by gordonbanderson** [comment]
All tests marked as skipped but no errors due to syntax or missing packages, see https://travis-ci.org/gordonbanderson/ss3gallery/builds/106472801

This is with 

``` bash
composer require "weboftalent/ss3gallery:~1"
```

**Comment by gordonbanderson** [comment]
I've fixed the dependent package builds also that were broken.  Can you have another go and let me know if you still see problems or not?

**Comment by Legin76** [comment]
Hi... Getting closer.  I've re-installed it.  The first time, I think I missed one of the dependencies of one of the dependencies.

I can create a page with image but when I try and add a gallery to it I get the error below.

[User Deprecated] GridFieldBulkUpload->setConfig is deprecated. GridFieldBulkUpload 'setConfig()' doesn't support 'folderName' anymore. Please use 'setUfConfig()', 'setUfSetup()' or 'setUfValidatorSetup()' instead. Called from GalleryPage->getCMSFields.

**Comment by gordonbanderson** [comment]
Sorry, we seem to be in different time zones (guessing you are UKish), I am in Thailand.  Saw the notification as I shot out the door earlier.  Will test manually tomorrow.

**Comment by Legin76** [comment]
That's no problem at all. I'm just happy you responded.

**Comment by gordonbanderson** [comment]
If you update the module it should now work in that it doesn't break.  Gridfield bulk editing tools was also missing from the requirements.

**Comment by Legin76** [comment]
I'm afraid at this point I can't help any more.. I'm not a programmer and have no idea about any of this.. I'm worried that if I keep going.. harm or more harm will be caused.

Hopefully someone that knows what their doing can make other changes to this  if needed.

**Comment by Legin76** [comment]
Almost there... It looks like the dependency / settings errors are fixed but I'm getting some strange things in the templates.  See the attached images

Folder Page
- The gallery image for the gallery pages are not appear to be displayed.
- It has Level test / and level 1

Gallery Page
- The page title (h1) appears as "Gallery Page Override"
- No Location found appears above the image.

![gallery-folder](https://cloud.githubusercontent.com/assets/999185/12843258/1a632960-cbf0-11e5-9c56-77e8e863635b.jpg)
![gallery-page](https://cloud.githubusercontent.com/assets/999185/12843259/1a6401fa-cbf0-11e5-8fcb-e6b47dc90105.jpg)

**Comment by Legin76** [comment]
Ok... The level test stuff and Gallery page override appear to be simple template things that I can fix.
I'm not sure what the map bit relates too but I can remove that too. Which just leaves the gallery image which uses the code below.. I just need it to output a gallery thumb at one size. Then we are laughing.

`<img class="shadowbox" alt="Photograph of $Top.Title"  data-interchange="[$PortletImage.CroppedFocusedImage(268,147).URL, (default)],[$PortletImage.CroppedFocusedImage(640,427).URL, (small)],[$PortletImage.CroppedFocusedImage(220,157).URL, (medium)],[$PortletImage.CroppedFocusedImage(268,179).URL, (large)]">`

There does appear to be some unused fields such as date and image credit but that are not an issue and I'm sure are there for future use.

**Comment by gordonbanderson** [comment]
I haven't got as far as the templates, wrestling with import of EXIF data at the moment.  I will need to add an extension hook and an optional extension to remove the map editing functionality.  Easy enough to do though :)

**Comment by Legin76** [comment]
Thanks for your help with this.. I used the old ss3 gallery on other sites. It's ideal for what I need.

**Comment by gordonbanderson** [comment]
The following, that you referred to, is image data for Zurb Foundation - it chooses the size depending on the size of the viewer screen, e.g. phone, panoramic monitor etc.

```
<img class="shadowbox" alt="Photograph of $Top.Title" data-interchange="[$PortletImage.CroppedFocusedImage(268,147).URL, (default)],[$PortletImage.CroppedFocusedImage(640,427).URL, (small)],[$PortletImage.CroppedFocusedImage(220,157).URL, (medium)],[$PortletImage.CroppedFocusedImage(268,179).URL, (large)]">
```

You will need something like:

```
<img src="$PortletImage.Width(300).URL" alt="whatever" title="whatever"/>
```

Oh and the CroppedFocusImage call is for another module, https://github.com/jonom/silverstripe-focuspoint - it allows a content editor to mark a point of an image as the main point of interest.  This then means images can be cropped to the same size and not have likes of heads chopped off.

Told you I hadn't tested this module properly.... but should be able to get it up and running out of the box fairly quickly.

**Comment by Legin76** [comment]
Haha... I didn't even spot that there was no src in that.

I get the impression you initially used it on your own site for something and then decided to upload it for others. I'm trying to avoid adding unnecessary add-ons at the moment to make future upgrades easier, so will avoid focuspoint for now.

$PortletImage.Width(300).URL doesn't output anything. I also tried $Image.Width(300).URL, with no luck though.

**Comment by Legin76** [comment]
I've worked out the gallery folder images after looking at the page with image code.

```
<% with MainImage %>
    <% with PaddedImage(300,240, 002144) %>
    <a href="$Link"><img class="introductoryImage" src="$URL" alt="$Top.Title" class="center"/></a>
    <% end_with %>
<% end_with %>
```

**Comment by gordonbanderson** [comment]
I've fixed most of the issues now, it should work 'out of the box'.  I've resurrected the original image box also using Pretty Photo library.  Documentation regarding extensions the main thing left to do now :)

**Comment by Legin76** [comment]
That's a huge improvement. Good going. I'm still not getting the folder images loading... 
It appears that $PortletImage.Fill(300,200).URL is not working.. I do have the portlet add-on installed too. It does work with the code mentioned above.

**Comment by gordonbanderson** [comment]
Oh maybe that is 3.2 only, which is what I am testing with

**Comment by Legin76** [comment]
Could be.. Thanks for your help... I'll tweak my templates to suit. Good work!

**Comment by gordonbanderson** [comment]
It should be possible to  add a method that checks for the existence of FocusPoint, 3.2 and then 3.1 methods and choose the best one accordingly.  And in such a manner that breaks do not occur.

**Comment by gordonbanderson** [comment]
Can you test the latest version.  I've added documentation and tests.

**Comment by Legin76** [comment]
Doh.. Fatal Error when running /dev/build?flush=ALL

Fatal error: Call to undefined function exif_read_data() in /home/swimming/public_html/ss3gallery/code/ImageMetaDataExtension.php on line 25

**Comment by gordonbanderson** [comment]
That's odd as it's a built in PHP function, see http://php.net/manual/en/function.exif-read-data.php

**Comment by Legin76** [comment]
What's also strange is that I've just gone back to Saturdays version and it's still giving me the same error... I'm wondering if there is something cached.

**Comment by Legin76** [comment]
Ok so it looks like Saturdays version had the error. I just didn't notice when I ran /dev/build?flush=ALL at the time.

**Comment by Legin76** [comment]
This may just be as simple as exif not being installed... Just recompiling apache and will report back.

**Comment by Legin76** [comment]
Bingo...  That's sorted it.. Everything is looking good for me out of the box now.

**Comment by gordonbanderson** [comment]
What system are you running on that you have to compile Apache out of curiosity.  And what is the name of the package so I can add it to the notes.

**Comment by Legin76** [comment]
It's a CentOS server with cpanel. It has php 5.6.17 installed. I had to go into the easy apache, Exhaustive Options List, check Exif and do a new build.
